lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600
    set_cookies:
        - 
            name: BEARER
            httpOnly: true
            secure: true
            samesite: 'lax'
            lifetime: 3600  # 1 hour