nelmio_api_doc:
    documentation:
        info:
            title: My API
            description: API routes for my mobile apps
            version: 1.0.0
        components:
            securitySchemes:
                MySecurityScheme:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - MySecurityScheme: []
    areas:
        path_patterns:
            - ^/(?!/doc$)